// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Password  string
	IsDeleted sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
